In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("placement.csv")

In [3]:
df

,cgpa,package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57
...,...,...
195,6.93,2.46
196,5.89,2.57
197,7.21,3.24
198,7.63,3.96


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   cgpa     200 non-null    float64
 1   package  200 non-null    float64
dtypes: float64(2)
memory usage: 3.3 KB


In [5]:
y=df["package"]

In [6]:
x=df.drop("package",axis=1)

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
x_train

,cgpa
79,7.18
197,7.21
38,8.62
24,6.53
122,5.12
...,...
106,6.13
14,7.73
92,7.90
179,7.14


In [9]:
y_train

79     3.00
197    3.24
38     4.36
24     2.71
122    2.01
       ... 
106    2.19
14     3.42
92     4.00
179    3.03
102    1.37
Name: package, Length: 160, dtype: float64

In [10]:
x_test

,cgpa
95,6.63
15,7.25
30,7.36
158,5.95
128,7.93
115,8.35
69,7.30
170,6.22
174,7.32
45,7.87


In [11]:
y_test

95     2.79
15     3.23
30     3.26
158    3.04
128    3.34
115    4.21
69     2.94
170    2.87
174    2.99
45     3.58
66     1.63
182    2.08
165    4.08
78     2.21
186    3.47
177    3.64
56     2.74
152    3.08
82     2.17
68     2.99
124    2.31
16     2.35
148    3.40
93     3.08
65     3.81
60     2.19
84     1.53
67     2.89
125    3.16
132    2.48
9      3.51
18     2.98
55     3.39
75     3.28
150    2.73
104    3.74
135    2.60
137    3.13
164    3.82
76     3.15
Name: package, dtype: float64

In [12]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
model=lr.fit(x_train,y_train)

In [13]:
model.coef_

array([0.57425647])

In [14]:
model.intercept_

np.float64(-1.0270069374542108)

In [71]:
import numpy as np
ypred = np.array(model.predict(x_test)) 

In [72]:
ypred

array([2.78031348, 3.13635249, 3.1995207 , 2.38981908, 3.52684689,
       3.76803461, 3.16506531, 2.54486832, 3.17655044, 3.4923915 ,
       1.90744364, 2.34962112, 3.6876387 , 2.75734322, 3.47516381,
       3.04447145, 2.32665086, 3.20526327, 2.17734418, 3.314372  ,
       2.45298729, 2.90090734, 3.32011456, 2.87219451, 3.33734226,
       2.19457187, 1.41932564, 2.7114027 , 3.18229301, 2.32665086,
       3.74506435, 2.95833298, 3.68189614, 2.97556068, 2.59080884,
       3.34882738, 2.47595755, 3.07318428, 4.17575671, 2.95833298])

In [73]:
from sklearn import metrics
print(metrics.mean_squared_error(ypred,y_test))
print(metrics.mean_absolute_error(ypred,y_test))
import math
print(math.sqrt(metrics.mean_squared_error(ypred,y_test)))
print(metrics.r2_score(ypred,y_test))

0.08417638361329656
0.23150985393278373
0.2901316659954521
0.733797338294438


In [79]:
model.predict([[6],[7.1]])

C:\Users\harsh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2.4185319 , 3.05021402])

In [81]:
df=pd.read_csv("car data.csv")

In [82]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0


In [85]:
df=df.drop("Car_Name",axis=1)

In [87]:
df["age"]=2026-df["Year"]

In [88]:
df

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,age
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,12
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,13
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,9
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,15
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,12
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0,10
297,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0,11
298,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0,17
299,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0,9


In [89]:
df=df.drop("Year",axis=1)

In [90]:
df

,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,age
0,3.35,5.59,27000,Petrol,Dealer,Manual,0,12
1,4.75,9.54,43000,Diesel,Dealer,Manual,0,13
2,7.25,9.85,6900,Petrol,Dealer,Manual,0,9
3,2.85,4.15,5200,Petrol,Dealer,Manual,0,15
4,4.60,6.87,42450,Diesel,Dealer,Manual,0,12
...,...,...,...,...,...,...,...,...
296,9.50,11.60,33988,Diesel,Dealer,Manual,0,10
297,4.00,5.90,60000,Petrol,Dealer,Manual,0,11
298,3.35,11.00,87934,Petrol,Dealer,Manual,0,17
299,11.50,12.50,9000,Diesel,Dealer,Manual,0,9


In [98]:
df=pd.get_dummies(df,drop_first=True)

In [99]:
df

,Selling_Price,Present_Price,Kms_Driven,Owner,age,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,3.35,5.59,27000,0,12,False,True,False,True
1,4.75,9.54,43000,0,13,True,False,False,True
2,7.25,9.85,6900,0,9,False,True,False,True
3,2.85,4.15,5200,0,15,False,True,False,True
4,4.60,6.87,42450,0,12,True,False,False,True
...,...,...,...,...,...,...,...,...,...
296,9.50,11.60,33988,0,10,True,False,False,True
297,4.00,5.90,60000,0,11,False,True,False,True
298,3.35,11.00,87934,0,17,False,True,False,True
299,11.50,12.50,9000,0,9,True,False,False,True


In [100]:
y=df["Present_Price"]

In [101]:
y

0       5.59
1       9.54
2       9.85
3       4.15
4       6.87
       ...  
296    11.60
297     5.90
298    11.00
299    12.50
300     5.90
Name: Present_Price, Length: 301, dtype: float64

In [102]:
x=df.drop("Present_Price",axis=1)

In [103]:
x

,Selling_Price,Kms_Driven,Owner,age,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,3.35,27000,0,12,False,True,False,True
1,4.75,43000,0,13,True,False,False,True
2,7.25,6900,0,9,False,True,False,True
3,2.85,5200,0,15,False,True,False,True
4,4.60,42450,0,12,True,False,False,True
...,...,...,...,...,...,...,...,...
296,9.50,33988,0,10,True,False,False,True
297,4.00,60000,0,11,False,True,False,True
298,3.35,87934,0,17,False,True,False,True
299,11.50,9000,0,9,True,False,False,True


In [104]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [105]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
model=lr.fit(x_train,y_train)

In [106]:
model.coef_

array([ 1.71595266e+00,  1.15897678e-05,  1.99992131e+00,  6.54719046e-01,
       -1.96393652e+00, -9.51002187e-01,  2.54716278e-01,  8.62489331e-01])

In [107]:
model.intercept_

np.float64(-8.773741161257604)

In [108]:
x.columns

Index(['Selling_Price', 'Kms_Driven', 'Owner', 'age', 'Fuel_Type_Diesel',
       'Fuel_Type_Petrol', 'Seller_Type_Individual', 'Transmission_Manual'],
      dtype='object')

In [109]:
model.predict(x_test)

array([-2.04409875, 15.16047348,  8.48023003,  3.87620404, 12.03856687,
       10.60159216,  0.78325366,  0.19978529, -1.12591183,  8.79869571,
       11.25912853,  2.17382013, 11.17537667, -2.87610789,  9.71080766,
        4.94427903,  2.32196627, 26.30224359, -1.79173704,  0.21827887,
        0.76358719, 11.22544236,  8.8458295 ,  6.33818501,  0.56840661,
        7.14427698,  8.88600831,  6.00416624, -0.52843568,  0.20741174,
        1.20461538, 12.86820501,  2.95306943,  6.94100304, 10.46899524,
        5.66324362,  9.92129649,  9.50715548,  5.2845707 , 10.34351425,
       11.77907238,  8.81940814,  6.93636709,  0.45656118,  8.86784779,
        1.30425403, 10.18412968, 10.68669428,  6.86059726,  5.21452932,
        7.97464876, -0.35101218, 37.3338384 , 34.79555141, 12.19472213,
       15.88275123,  7.82945636, 13.3674654 ,  8.42040082,  9.69502711,
        0.7662887 ])

In [111]:
import numpy as np
ypred = np.array(model.predict(x_test)) 

In [112]:
from sklearn import metrics
print(metrics.mean_squared_error(ypred,y_test))
print(metrics.mean_absolute_error(ypred,y_test))
import math
print(math.sqrt(metrics.mean_squared_error(ypred,y_test)))
print(metrics.r2_score(ypred,y_test))

10.64359519627365
2.107262281576755
3.2624523285825417
0.8105826322716216


In [114]:
model.predict([[5.5,28000,0,5,False,False,False,False],[5.8,20000,1,4,1,False,False,1]])

C:\Users\harsh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.26210719, 4.92792993])